name: Publish Release to npm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ animetric, arcane, arcane-core, colorimetric, core, katon-theme, shortcuts, widgets, widgets-ui ]

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Debug - Vérifier les fichiers et dossiers
        run: ls -la packages/

      - name: Install pnpm globally
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install `ts-add-js-extension`
        run: pnpm add ts-add-js-extension

      - name: Build packages
        run: |
            cd packages/!${{ matrix.package }}
            cd packages/${{ matrix.package }}
            pnpm run build

      - name: Configure npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          echo "@protorians:registry=https://registry.npmjs.org/" >> ~/.npmrc

      - name: Publish to NPM
        run: |
          cd ./packages/${{ matrix.package }}
          npm publish --access=public 

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
